spring:
  application:
        name: dbp-management-platform
  datasource:
    url: jdbc:mysql://192.168.100.166:3306/api_gateway?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 300 #最大连接池数量
    initialSize: 5 #初始化时建立物理连接的个数
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    minIdle: 10 #最小连接池数量
    timeBetweenEvictionRunsMillis: 60000 #Destroy线程会检测连接的间隔时间
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 'x' #用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。
    testOnBorrow: false # 申请连接时执行validationQuery检测连接是否有效， 做了这个配置会降低性能。
    testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: true #是否缓存preparedStatement，也就是PSCache
    maxOpenPreparedStatements: 20
    defaultAutoCommit: true
    removeAbandoned: true #对于长时间不使用的连接强制关闭
    removeAbandonedTimeout: 600 #超过10分钟开始关闭空闲连接,秒
    logAbandoned: true  #将当前关闭动作记录到日志    

server:
  port: 8080
eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
#      defaultZone: http://localhost:1001/eureka/
      defaultZone: http://root:123456@106.2.20.167:8100/eureka/
#系统自定义的配置
system:
  sysName: dbp-management-platform
  internal:
    show: true #显示内部错误信息